version: '3.8'

services:
  reportdb:
    image: postgres:17
    container_name: SeturReportDbContainer
    restart: always
    ports:
      - "1511:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456aA*
      POSTGRES_DB: ReportDb
    volumes:
      - ./dump-report.sql:/docker-entrypoint-initdb.d/init.sql
