version: '3.8'

services:
  db:
    image: postgres:17
    container_name: SeturComposeContactDb
    restart: always
    ports:
      - "1510:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456aA
      POSTGRES_DB: ContactDb
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/init.sql
